# This workflow will build a .NET project and run the available unit tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on:  ubuntu-latest
    strategy:
      matrix:
        include:
        - dotnet-version: '3.1.x'
          tfm: 'netcoreapp3.1'
          
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore -p:TargetFramework=${{ matrix.tfm }}
      
    - name: Run Build
      run: dotnet build
      
    - name: Run UnitTests
      run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}" -f=${{ matrix.tfm }}
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
